### ISSUE TITLE
Streql dependency will not install on windows 10 

### ISSUE THREAD

**Issue by sabotagebeats** [bigcommerce/hello-world-app-python-flask#23]
### Expected behavior
Able to install and run dependencies to attempt to run app

### Actual behavior
Streql does not install on windows 10

### Steps to reproduce behavior
pip install streql on windows 10 python 2.7 powershell

Please remove streql if not necessary to run application as streql install is broken. 

https://github.com/PeterScott/streql/issues/1

**Comment by bookernath** [comment]
This is fixed by https://github.com/bigcommerce/bigcommerce-api-python/commit/305fa183616a1b5899e78c2024c27c95a12f8683

I've also updated this sample app to take advantage of the latest library.
