### ISSUE TITLE
flask sessions cookie error on Chrome, Opera, Brave, (all with third party cookies enabled) but not an issue with Safari or Firefox

### ISSUE THREAD

**Issue by argoapps** [bigcommerce/hello-world-app-python-flask#29]
Yeah the specific error you're seeing is flask saying "hey we couldn't find (this value) in the session cookie", probably because there was no session cookie. So now we're back to the frontend, figuring out if the cookie is available in the right place...

You might try opening your app URL directly and checking for this cookie:

![image](https://user-images.githubusercontent.com/8922457/44128695-f198ce86-a009-11e8-9a28-a9d00ad97388.png)

_Originally posted by @bookernath in https://github.com/bigcommerce/hello-world-app-python-flask/issues/13#issuecomment-413076255_

I'm getting a similar Keyword Error at the flask/session.py line 84

return super(SecureCookieSession, self).__getitem__(key)

KeyError: 'storeuserid'

third party cookies are enabled in Brave, Chrome and Opera browsers, but hasn't made a difference.  Firefox works fine, Safari doesn't at first but has a popup that says enable third party cookies and once clicked it works.  Any ideas?  Thanks in advance

**Comment by argoapps** [comment]
If I disable samesite cookies in Brave and Chrome it works but is there a way to fix this issue without having to do this manually?  I have looked at something about including SameSite=None somewhere but I don't know where to put it

<img width="725" alt="Screenshot 2021-03-22 at 17 58 52" src="https://user-images.githubusercontent.com/80706503/112036263-5545cf80-8b38-11eb-9abd-d7db45d08d70.png">

**Comment by argoapps** [comment]
I did find this supposed solution but I can't seem to get it working.

Even with the latest version of flask and Werkzeug 1.0 which is supposed to solve the issue doesn't but there seems to be a workaround here.  Any ideas on how to implement it with bigcommerce/hello-world-app-python-flask?

https://stackoverflow.com/questions/62992831/python-session-samesite-none-not-being-set?answertab=active#tab-top

**Comment by harjap-singh-katapult** [comment]
Was anyone able to resolve the issue? Tried out a few ways but still stuck on this.

**Comment by bookernath** [comment]
Fixed by https://github.com/bigcommerce/hello-world-app-python-flask/commit/ead6d9073a7fa238522e05b062d44065321b4970
