### ISSUE TITLE
Requested runtime 'python-3.8.10' is not available for this stack (heroku-22)

### ISSUE THREAD

**Issue by soufianechalouh** [bigcommerce/hello-world-app-python-flask#37]
### Expected behavior

Build success

### Actual behavior

Build fails with error logs:

` !     Requested runtime 'python-3.8.10' is not available for this stack (heroku-22).
 !     For supported versions, see: https://devcenter.heroku.com/articles/python-support
 !     Push rejected, failed to compile Python app.
 !     Push failed`

### Steps to reproduce behavior
 

1. Click deploy to Heroku
2. Fill the details
3. Click deploy app

**Comment by bookernath** [comment]
Fixed by https://github.com/bigcommerce/hello-world-app-python-flask/commit/8044c391c954b23436e32c65d6224725e0b9d2f4
